const colleges = [
  { name: "Government College of Technology (Autonomous)" },
  { name: "PSG College of Technology (Autonomous)" },
  { name: "Coimbatore Institute of Technology (Autonomous)" },
  { name: "Anna University Regional Campus - Coimbatore" },
  { name: "Rathinam Technical Campus" },
  { name: "Asian College of Engineering and Technology" },
  { name: "Sri Ranganathar Institute of Engineering and Technology" },
  { name: "Dhaanish Ahmed Institute of Technology" },
  { name: "Pollachi Institute of Engineering and Technology" },
  { name: "V S B College of Engineering Technical Campus" },
  { name: "Suguna College of Engineering, Kalappatti Road" },
  { name: "Arjun College of Technology" },
  { name: "PSG Institute of Technology and Applied Research" },
  { name: "Christ The King Engineering College" },
  { name: "Sree Sakthi Engineering College" },
  { name: "Coimbatore Institute of Engineering and Technolgoy (Autonomous)" },
  {
    name: "Dr. Mahalingam College of Engineering and Technology (Autonomous),",
  },
  { name: "Hindusthan College of Engineering and Technology (Autonomous)" },
  { name: "Karpagam College of Engineering (Autonomous)" },
  { name: "Kumaraguru College of Technology (Autonomous)" },
  { name: "Park College of Engineering and Technology" },
  { name: "Sri Krishna College of Enginering and Technology (Autonomous) " },
  { name: "Sri Ramakrishna Engineering College (Autonomous)" },
  { name: "Tamilnadu College of Engineering" },
  { name: "Sri Krishna College of Technology (Autonomous) " },
  { name: "Sri Ramakrishna Institute of Technology (Autonomous)" },
  { name: "SNS College of Technology (Autonomous)" },
  { name: "Sri Shakthi Institute of Engineering and Technology (Autonomous)" },
  { name: "Nehru Institute of Engineering and Technology" },
  { name: "R V S College of Engineering and Technology" },
  { name: "Info Institute of Engineering" },
  { name: "SNS College of Engineering (Autonomous)" },
  { name: "Karpagam Institute of Technology" },
  { name: "Dr. N G P Institute of Technology" },
  { name: "Sri Sai Ranganathan Engineering College" },
  { name: "Sri Eshwar College of Engineering (Autonomous)" },
  { name: "Hindusthan Institute of Technology (Autonomous)" },
  { name: "P A College of Engineering and Technology (Autonomous)" },
  { name: "Dhanalakshmi Srinivasan College of Engineering" },   
  { name: "Adithya Institute of Technology" },
  { name: "Kathir College of Engineering" },
  { name: "Easa College of Engineering and Technology" },
  { name: "KIT - Kalaignar Karunanidhi Institute of Technology (Autonomous)" },
  { name: "PPG Institute of Technology" },
  { name: "Nehru Institute of Technology" },
  { name: "United Institute of Technology" },
  { name: "Jansons Institute of Technology" },
  { name: "Akshaya College of Engineering and Technology" },
  { name: "K P R Institute of Engineering and Technology (Autonomous)" },
  { name: "Park College of Technology" },
  { name: "J C T College of Engineering and Technology" },
  { name: "Studyworld College of Engineering" },
  { name: "C M S College of Engineering and Technology" },
  { name: "R V S Technical Campus-Coimbatore" },
  //   Eng College
  // Arts College
  { name: "Sri Krishna Arts and Science College" },
  { name: "Hindusthan College of Arts and Science" },
  { name: "Sri Ramakrishna College of Arts and Science" },
  { name: "CBM College of Arts and Science" },
  { name: "Sri Ramakrishna College of Arts & Science For Women " },
  { name: "CMS College of Science and Commerce" },
  { name: "Rathinam College of Arts and Science" },
  { name: "PSG College of Arts and Science" },
  { name: "SMS College Of Arts and Science" },
  { name: "Kongunadu Arts and Science College" },
  { name: "Bharathiar University" },
  { name: "Dr GR Damodaran College of Science" },
  { name: "Nirmala College for Women" },
  { name: "PSGR Krishnammal College for Women" },
  { name: "Government Arts College" },
  { name: "Sri Ramakrishna Mission Vidyalaya College of Arts and Science" },
  { name: "P.S.G College of Technology " },
  { name: "Dr. N.G.P. Arts and Science College" },
  { name: "Nehru Arts and Science College" },
  { name: "Dr. SNS Rajalakshmi College of Arts and Science" },
  { name: "Karunya Institute of Technology and Sciences" },
  { name: "Karpagam Academy of Higher Education" },
  { name: "Karunya School of Management, Karunya University" },
  { name: "Sri Ramakrishna Mission Vidyalaya College of Education" },
  {
    name: "Avinashilingam Institute For Home Science and Higher Education For Women",
  },
  { name: "Bishop Appasamy College of Arts and Science" },
  { name: "V.L.B. Janakiammal College of Arts and Science" },
  { name: "Amrita Vishwa Vidyapeetham" },
  { name: "Amrita School of Business " },
  { name: "RVS Institute of Management Studies and Research " },
  { name: "AJK College of Arts and Science " },
  { name: "KG College of Arts and Science" },
  { name: "K.S.G. College of Arts and Science" },
  { name: "RVS College of Arts and Science" },
  {
    name: "Sri Jayendra Saraswathy Maha Vidyalaya College of Arts and Science",
  },
  { name: "South India Baptist Bible College and Seminary" },
  { name: "Lalit Kalakshetra, Raviraj Institute for Art and Culture" },
  { name: "Mayuri Cultural Arts Centre" },
  { name: "Salim Ali Centre for Ornithology and Natural History " },
  { name: "Amrita School of Communication" },
  { name: "CMS Institute of Management Studies" },
  { name: "G .R. Govindarajulu College of Education" },
  { name: "Indira Gandhi College of Distance Education" },
  { name: "Shri Nehru Maha Vidyalaya College of Arts and Science " },
  { name: "Indian Statistical Institute" },
  { name: "Maharaja Arts and Science College" },
  { name: "Michael Job College of Arts & Science for Women" },
  { name: "Pioneer College of Arts & Science" },
  { name: "Bharathiar University, School of Distance Education" },
  { name: "Kathir College of Education" },
  { name: "Maruthi College of Physical Education" },
  { name: "School of Commerce, Bharathiar University" },
  { name: "Amrita School of Arts and Sciences" },
  { name: "Kumaraguru College of Liberal Arts and Science" },
  { name: "Apex Institute of Multimedia," },
  { name: "PSG Institute of Advanced Studies" },
  { name: "Clusters Media College" },
  { name: "Pollachi College of Arts and Science" },
  { name: "Nehru Group of Institutions" },
  { name: "Sri Krishna Adithya College of Arts and Science" },
  { name: "Nallamuthu Gounder Mahalingam College" },
  { name: "Kathir College of Arts and Science" },
  { name: "GRD Institute of Management" },
  { name: "Suguna College of Arts & Science" },
  { name: "Cheran Group of Institutions" },
  { name: "KG College of Physiotherapy" },
];
